### ISSUE TITLE
/Signup , POST

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#10]
#### Description
When a new user signs up on the site it has to insert a new user into the database with validated data and hashed password.

---
#### Files
- Database -> Queries -> addUserQuery.js
- Database -> Queries -> index.js
- Controllers -> addUser.js 
- Controllers -> index.js
- Routes -> index.js -> app.post();
---

#### Tasks

- [x] Create DB query to add a new user to the database 
- [x] Import the query in controllers from DB>QUERIES>index.js and insert data with validation and hashing. 
- [x] Create POST Route in Routes>index.js
