### ISSUE TITLE
/Signin , POST

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#11]
#### Description
When the user clicks the sign in it has to check and compare the data with the stored one then logged him on if true with user token or alert errors.

---
#### Files
- Database -> Queries -> getUserData.js
- Database -> Queries -> index.js
- Controllers -> signIn.js 
- Controllers -> index.js
- Routes -> index.js -> app.post();
---

#### Tasks

- [x] Create a DB query to get the user data from the database. 
- [x] Import the query in controllers from DB>QUERIES>index.js and compare data with validation and hashing.compare().
- [x] Create POST Route in Routes>index.js
