### ISSUE TITLE
/addProduct , POST

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#12]
#### Description
When seller click on add new product it has to store a new product in the database so can any user see it on the landing page

---
#### Files
- Database -> Queries -> addProductQuery.js
- Database -> Queries -> index.js
- Controllers -> addProduct.js 
- Controllers -> index.js
- Routes -> index.js -> app.post();
---

#### Tasks

- [ ] Create DB query to add a new item to the database. 
- [ ] Import the query in controllers from DB>QUERIES>index.js and validate the inputs then add to DB.
- [ ] Create POST Route in Routes>index.js
