### ISSUE TITLE
/AddToCart , POST

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#13]
#### Description
When the user click on the + or add to cart button it has to add the product in his cart so he can see it on the cart page
  
---
#### Files
- Database -> Queries -> addCartQuery.js
- Database -> Queries -> index.js
- Controllers -> addCart.js 
- Controllers -> index.js
- Routes -> index.js -> app.post();
---

#### Tasks

- [x] Create DB query to add a new item to the cart table in the database. 
- [x] Import the query in controllers from DB>QUERIES>index.js and add it to the cart.
- [x] Create POST Route in Routes>index.js
