### ISSUE TITLE
/product/:productId , GET

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#14]
#### Description
When the user enters any product page he can see the data about this product and the comments or reviews on it

#### Files
- Database -> Queries -> getProductQuery.js
- Database -> Queries -> index.js
- Controllers -> getProduct.js 
- Controllers -> index.js
- Routes -> index.js -> app.get();
---

#### Tasks

- [x] Create DB query to get the product from the database. 
- [x] Import the query in controllers from DB>QUERIES>index.js and return to the front.
- [x] Create GET Route in Routes>index.js
