### ISSUE TITLE
/UserProducts , GET

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#15]
#### Description
When the user enters the cart page he can see all added to cart products the user id can get it from the token.

#### Files
- Database -> Queries -> getUserCartQuery.js
- Database -> Queries -> index.js
- Controllers -> getUserCart.js 
- Controllers -> index.js
- Routes -> index.js -> app.get();

---

#### Tasks

- [x] Create a DB query to get the product for every user from the database. 
- [x] Import the query in controllers from DB>QUERIES>index.js and return to the front.
- [x] Create GET Route in Routes>index.js
