### ISSUE TITLE
/deletePorduct/:productId , DELETE

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#16]
#### Description
When the user clicks on the delete icon he can delete the product from his cart.

---
#### Files
- Database -> Queries -> deleteProductQuery.js
- Database -> Queries -> index.js
- Controllers -> deleteProduct.js 
- Controllers -> index.js
- Routes -> index.js -> app.delete();

---

#### Tasks

- [x] Create DB query to delete the product from the DB.
- [x] Import the query in controllers from DB>QUERIES>index.js and return to the front the updated cart.
- [x] Create DELETE Route in Routes>index.js
