### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#7]
#### Description
connect the database with the express server.

---
#### Files
- connection -> index.js
---

#### Tasks

- [x] Edit NODE_ENV in package.json
- [x] Use 'pg' module
- [x] Create new pool with all modes
