### ISSUE TITLE
/Products , GET

### ISSUE THREAD

**Issue by umarsalah** [GSG-G10/gifty#9]
#### Description
When the user enters the landing page has to see all the products stored in the database.

 ---

#### Files
- Database -> Queries -> getProductsQuery.js
- Database -> Queries -> index.js
- Controllers -> getProducts.js 
- Controllers -> index.js
- Routes -> index.js -> router.get();
---

#### Tasks

- [x] Create DB query to get the products from the database 
- [x] Import the query in controllers from DB>QUERIES>index.js  and return the data
- [x] Create GET Route in Routes>index.js
